/**
 * Daniel Pedrosa Montes © 2024
 * 
 * GNU AFFERO GENERAL PUBLIC LICENSE
 */

#ifdef MB85RS4MT_MFHMI

#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

#include <MFHMI.h>
#include <MB85RS4MT.h>

static volatile uint8_t sent = 0;
static volatile uint8_t recv = 0;

static void spi_cb(spi_callback_args_t* args) {
    if (args->event == SPI_EVENT_TRANSFER_COMPLETE) {
        sent = 1;
        recv = 1;
    }
}

static void open(void) {
    static spi_callback_args_t cb_args;
    R_SPI_Open(g_spi_MB85RS4MT.p_ctrl, g_spi_MB85RS4MT.p_cfg);
    R_SPI_CallbackSet(g_spi_MB85RS4MT.p_ctrl, spi_cb, 0, &cb_args);
}

static void close(void) {
    R_SPI_Close(g_spi_MB85RS4MT.p_ctrl);
}

static void cs_assert(void) {
    R_BSP_PinAccessEnable();
    R_BSP_PinWrite(BSP_IO_PORT_01_PIN_11, BSP_IO_LEVEL_LOW);
    R_BSP_PinAccessDisable();
}

static void cs_deassert(void) {
    R_BSP_PinAccessEnable();
    R_BSP_PinWrite(BSP_IO_PORT_01_PIN_11, BSP_IO_LEVEL_HIGH);
    R_BSP_PinAccessDisable();
}

static void wp_assert(void) {
    R_BSP_PinAccessEnable();
    R_BSP_PinWrite(BSP_IO_PORT_04_PIN_00, BSP_IO_LEVEL_HIGH);
    R_BSP_PinAccessDisable();
}

static void wp_deassert(void) {
    R_BSP_PinAccessEnable();
    R_BSP_PinWrite(BSP_IO_PORT_04_PIN_00, BSP_IO_LEVEL_LOW);
    R_BSP_PinAccessDisable();
}

static void write(const uint8_t* data, uint32_t len) {
    sent = 0;
    R_SPI_Write(g_spi_MB85RS4MT.p_ctrl, data, len, SPI_BIT_WIDTH_8_BITS);
    while (!sent) {}
}

static void read(uint8_t* data, uint32_t len) {
    recv = 0;
    R_SPI_Read(g_spi_MB85RS4MT.p_ctrl, data, len, SPI_BIT_WIDTH_8_BITS);
    while (!recv) {}
}

void watchdog_refresh(void);
void watchdog_refresh(void) {
    MFHMI_watchdog_refresh();
}

void MB85RS4MT_test_pull_ID(MB85RS4MT_t* fram);
void MB85RS4MT_test_push_and_pull_status_register(MB85RS4MT_t* fram);
void MB85RS4MT_test_block_protect_err(MB85RS4MT_t* fram);
void MB85RS4MT_test_write_and_read_all_bytes(MB85RS4MT_t* fram);

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void) {
    MFHMI_init(kMFHMI_Disabled);
    MFHMI_set_LED(0);

    MB85RS4MT_t fram = {
        ._open = open,
        ._close = close,
        ._cs_assert = cs_assert,
        ._cs_deassert = cs_deassert,
        ._wp_assert = wp_assert,
        ._wp_deassert = wp_deassert,
        ._write = write,
        ._read = read,
        .status = {0},
    };

    MB85RS4MT_test_pull_ID(&fram);
    MB85RS4MT_test_push_and_pull_status_register(&fram);
    MB85RS4MT_test_block_protect_err(&fram);
    for (int i = 0 ; i < 32; i++) {
        MB85RS4MT_test_write_and_read_all_bytes(&fram);
    }

    while (1) {
        MFHMI_set_LED(1);
        MFHMI_watchdog_refresh();
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event) {
    (void)event;
}

#endif // MB85RS4MT_MFHMI
