name: "Formato MarkDown correcto"

on:
  push:
    paths:
      - 'docs/**.md'

jobs:
  comprueba:
    runs-on: ubuntu-latest
    container:
      image: pipelinecomponents/markdownlint:latest
    steps:
      - uses: actions/checkout@v4
      - run: apk add --no-cache make
      - name: Comprueba formato
        working-directory: ./docs
        run: make formato
